/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package erg;

import java.io.IOException;
import java.net.URL;
import java.util.Optional;
import java.util.ResourceBundle;

import javafx.application.Application;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.ButtonType;
import javafx.scene.control.SplitPane;
import javafx.scene.layout.Region;
import javafx.stage.Stage;
import javafx.stage.WindowEvent;

public class App extends Application implements Initializable {

    @FXML
    SplitPane main_split;

    @Override
    public void initialize(URL url, ResourceBundle rb) {

    }

    @Override
    public void start(Stage stage) {
        Parent root = null;

        try {
            root = FXMLLoader.load(getClass().getResource("/erg/main.fxml"));

        } catch (IOException e) {
            System.out.println(e.getCause());
            System.out.println(e.getMessage());
            throw new RuntimeException("Could not load main.fxml ");
        }

        Scene scene = new Scene(root, 1280, 720);

        stage.setTitle("Smart Home App v1.0");
        stage.setScene(scene);

        // stage.getScene().getWindow().addEventFilter(WindowEvent.WINDOW_CLOSE_REQUEST, this::closeWindowEvent);
        stage.show();

        Alert welcome = new CustomAlert(Alert.AlertType.NONE);
        welcome.setContentText("Welcome User!");
        welcome.getButtonTypes().add(ButtonType.CLOSE);
        welcome.show();
    }

    public static void main(String[] args) {
        launch(args);
    }

    @FXML
    void do_stuff() {
        System.out.print("lel");
    }
}
