/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package erg;

import java.io.IOException;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage stage) {
        String javaVersion = System.getProperty("java.version");
        String javafxVersion = System.getProperty("javafx.version");

        Label l = new Label("Hello, JavaFX " + javafxVersion + ", running on Java " + javaVersion);

        try {
            Parent root = FXMLLoader.load(getClass().getResource("/main.fxml"));
            Scene scene = new Scene(root, 640, 480);
            stage.setTitle("testing title");
            stage.setScene(scene);
            stage.show();
        } catch (IOException e) {

        }
    }

    public static void main(String[] args) {
        launch(args);
    }

}
